name: Build

on: 
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - run: dotnet build -c Debug

    - uses: actions/upload-artifact@v4
      with:
        name: Raicuparta.QuantumSpaceBuddies
        path: .\QSB-NH\Bin\Debug